name: xplot
channels:
  - conda-forge
dependencies:
  - clang=11.1
  - clang-11=11.1
  - clang-tools=11.1
  - clangdev=11.1
  - clangxx=11.1
  - libclang=11.1
  - libclang-cpp=11.1
  - python-clang=11.1
  - lld=11.1
  - libstdcxx-devel_linux-64
  - cmake
  - matplotlib
